/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121317",
        "surface-dim": "#121317",
        "surface-bright": "#38393d",
        "surface-container-lowest": "#0d0e12",
        "surface-container-low": "#1a1b1f",
        "surface-container": "#1e1f24",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343439",
        "on-surface": "#e3e2e7",
        "on-surface-variant": "#c8c4d7",
        "inverse-surface": "#e3e2e7",
        "inverse-on-surface": "#2f3034",
        "outline": "#928ea0",
        "outline-variant": "#474554",
        "surface-tint": "#c6bfff",
        "primary": "#c6bfff",
        "on-primary": "#2900a0",
        "primary-container": "#6c5ce7",
        "on-primary-container": "#faf6ff",
        "inverse-primary": "#5847d2",
        "secondary": "#aec6ff",
        "on-secondary": "#002e6a",
        "secondary-container": "#0061d1",
        "on-secondary-container": "#dbe4ff",
        "tertiary": "#c6c6ce",
        "on-tertiary": "#2f3036",
        "tertiary-container": "#717178",
        "on-tertiary-container": "#f8f7ff",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e4dfff",
        "primary-fixed-dim": "#c6bfff",
        "on-primary-fixed": "#160066",
        "on-primary-fixed-variant": "#4029ba",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#aec6ff",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-fixed": "#e3e1ea",
        "tertiary-fixed-dim": "#c6c6ce",
        "on-tertiary-fixed": "#1a1b21",
        "on-tertiary-fixed-variant": "#46464d",
        "background": "#121317",
        "on-background": "#e3e2e7",
        "surface-variant": "#343439",
      },
      fontFamily: {
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'title-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'mono-label': ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
}
