// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function CopyToAssetSandbox(arg1) {
  return window['go']['main']['App']['CopyToAssetSandbox'](arg1);
}

export function EngineHealth() {
  return window['go']['main']['App']['EngineHealth']();
}

export function GetBrokerBaseURL() {
  return window['go']['main']['App']['GetBrokerBaseURL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultTemplatePath() {
  return window['go']['main']['App']['GetDefaultTemplatePath']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAssetSandbox() {
  return window['go']['main']['App']['ListAssetSandbox']();
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function PickAssetFile(arg1) {
  return window['go']['main']['App']['PickAssetFile'](arg1);
}

export function PickMoBlendFile() {
  return window['go']['main']['App']['PickMoBlendFile']();
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function StartEngine(arg1) {
  return window['go']['main']['App']['StartEngine'](arg1);
}

export function StopEngine() {
  return window['go']['main']['App']['StopEngine']();
}
