// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1:string):Promise<void>;

export function CopyToAssetSandbox(arg1:Array<string>):Promise<Array<string>>;

export function EngineHealth():Promise<Record<string, any>>;

export function GetBrokerBaseURL():Promise<string>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDefaultTemplatePath():Promise<string>;

export function GetRecentProjects():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDevTools():Promise<void>;

export function PickMoBlendFile():Promise<string>;

export function Reload():Promise<void>;

export function SetConfig(arg1:Record<string, any>):Promise<void>;

export function StartEngine(arg1:string):Promise<void>;

export function StopEngine():Promise<void>;
